---
output:
  pdf_document: default
---

```{r, include= FALSE}
library(tidyverse)
```


```{r}
#| echo: false
#| fig-cap: Test 1

# Test 1
set.seed(111)

df <- tibble(
  Day = 1:100,
  Matt = rpois(100, lambda = 37),
  Ash = rpois(100, lambda = 40),
  Jacki = rpois(100, lambda = 25),
  Rol = rpois(100, lambda = 54),
  Mike = rpois(100, lambda = 16)
)

df_long <- df %>% pivot_longer(cols = -Day, names_to = "Person", values_to = "Value")

# Plot the data
ggplot(df_long, aes(x = Day, y = Value, color = Person)) +
  geom_line() +
  #facet_wrap(~ Person) +
  labs(x = "Day", y = "Value", title = "Pages Read over 100 Days") +
  theme_minimal()

```


```{r}
#| echo: false
#| fig-cap: Test 2

# Test 2
set.seed(222)

df <- tibble(
  Day = 1:100,
  Matt = rpois(100, lambda = 37),
  Ash = rpois(100, lambda = 40),
  Jacki = rpois(100, lambda = 25),
  Rol = rpois(100, lambda = 54),
  Mike = rpois(100, lambda = 16)
)

df_long <- df %>% pivot_longer(cols = -Day, names_to = "Person", values_to = "Value")

# Plot the data
ggplot(df_long, aes(x = Day, y = Value, color = Person)) +
  geom_line() +
  #facet_wrap(~ Person) +
  labs(x = "Day", y = "Value", title = "Pages Read over 100 Days") +
  theme_minimal()
```


```{r}
#| echo: false
#| fig-cap: Test 3

# Test 3
set.seed(333)

df <- tibble(
  Day = 1:100,
  Matt = rpois(100, lambda = 37),
  Ash = rpois(100, lambda = 40),
  Jacki = rpois(100, lambda = 25),
  Rol = rpois(100, lambda = 54),
  Mike = rpois(100, lambda = 16)
)

df_long <- df %>% pivot_longer(cols = -Day, names_to = "Person", values_to = "Value")

# Plot the data
ggplot(df_long, aes(x = Day, y = Value, color = Person)) +
  geom_line() +
  #facet_wrap(~ Person) +
  labs(x = "Day", y = "Value", title = "Pages Read over 100 Days") +
  theme_minimal()
```

```{r}
#| echo: false
#| fig-cap: Test 4

# Test 4
set.seed(444)

df <- tibble(
  Day = 1:100,
  Matt = rpois(100, lambda = 37),
  Ash = rpois(100, lambda = 40),
  Jacki = rpois(100, lambda = 25),
  Rol = rpois(100, lambda = 54),
  Mike = rpois(100, lambda = 16)
)

df_long <- df %>% pivot_longer(cols = -Day, names_to = "Person", values_to = "Value")

# Plot the data
ggplot(df_long, aes(x = Day, y = Value, color = Person)) +
  geom_line() +
  #facet_wrap(~ Person) +
  labs(x = "Day", y = "Value", title = "Pages Read over 100 Days") +
  theme_minimal()
```

```{r}
#| echo: false
#| fig-cap: Test 5

# Test 5
set.seed(555)

df <- tibble(
  Day = 1:100,
  Matt = rpois(100, lambda = 37),
  Ash = rpois(100, lambda = 40),
  Jacki = rpois(100, lambda = 25),
  Rol = rpois(100, lambda = 54),
  Mike = rpois(100, lambda = 16)
)

df_long <- df %>% pivot_longer(cols = -Day, names_to = "Person", values_to = "Value")

# Plot the data
ggplot(df_long, aes(x = Day, y = Value, color = Person)) +
  geom_line() +
  #facet_wrap(~ Person) +
  labs(x = "Day", y = "Value", title = "Pages Read over 100 Days") +
  theme_minimal()
```